use_frameworks!

platform :ios, '9.0'

target 'JLMainProject_Example' do
  pod 'JLMainProject', :path => '../'

  target 'JLMainProject_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
